agentConfig:
  controllerAddr: ":8081"
  natsFilestoreDir: "src/main/resources/datastore"
  natsStoreType: "FILE"
  startNATS: True
  startTransport: True
  startController: True
groundworkConfig:
  host: "localhost:80"
  account: "RESTAPIACCESS"
  password: "***REMOVED***"
  appName: "gw8"
