agentConfig:
  controllerAddr: ":8081"
  natsAckWait: 15
  natsFilestoreDir: "src/main/resources/datastore"
  natsStoreType: "FILE"
  natsHost: ":4222"
  startNats: True
  startTransport: True
  startController: True
  loggingLevel: 0
gwConfigs:
  -
    host: "localhost:80"
    account: "RESTAPIACCESS"
    password: "***REMOVED***"
    appName: "gw8"
  -
    host: "localhost:88"
    account: "RESTAPIACCESS"
    password: "***REMOVED***"
    appName: "gw8"
