actions:
  synchronizeInventoryAction:
    entrypoint: "http://localhost/api/synchronizer"
  sendResourceWithMetricsAction:
    entrypoint: "http://localhost/api/monitoring"
config:
  host: "gw8-host"
  account: "RESTAPIACCESS"
  password: "***REMOVED***"
  ssl: True
  port: 8080