connector:
  agentId: "3dcd9a52-949d-4531-a3b0-b14622f7dd39"
  appName: "tng"
  appType: "VEMA"
  controllerAddr: ":8099"
  natsAckWait: 30
  natsMaxInflight: 2147483647 # math.MaxInt32
  natsFilestoreDir: "src/main/resources/datastore"
  natsStoreType: "FILE"
  natsHost: ":4222"
  logLevel: 2
dsConnection:
  hostName: "localhost:3001"
  userName: "RESTAPIACCESS"
  password: "***REMOVED***"
gwConnections:
  -
    hostName: "localhost:80"
    userName: "RESTAPIACCESS"
    password: "***REMOVED***"
  -
    hostName: "localhost:88"
    userName: "RESTAPIACCESS"
    password: "***REMOVED***"
