connector:
  agentId: "***REMOVED***"
  appName: "tng"
  appType: "VEMA"
  controllerAddr: "0.0.0.0:8099"
  natsAckWait: 30
  natsMaxInflight: 2147483647 # math.MaxInt32
  natsFilestoreDir: "src/main/resources/datastore"
  natsStoreType: "FILE"
  natsHost: ":4222"
  logLevel: 2
dsConnection:
  hostName: "dalekservices:3001"
