agentConfig:
  addr: ":8081"
  startNATS: True
  startTransport: True
  startController: False
groundworkConfig:
  host: "localhost:80"
  account: "RESTAPIACCESS"
  password: "***REMOVED***"
groundworkActions:
  connect:
    entrypoint: "/api/auth/login"
  disconnect:
    entrypoint: "/api/auth/logout"
  synchronizeInventory:
    entrypoint: "/api/synchronizer"
  sendResourceWithMetrics:
    entrypoint: "/api/monitoring"
  validateToken:
    entrypoint: "/api/auth/validatetoken"
