---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: influxdb-auth
  namespace: picasa-local
data:
  admin-password: V1JMUkJwU21MdWxkQVZ1aVlVVDZmQXd5TTA5R1BOTXk=
  admin-token: RE9FdEU5bWdMRFNhVUN3ZWNJYmZZSHNEZ3R0cTV6cnc=
  influxdb-user: aW5mbHV4ZGF0YQ==
  influxdb-password: V1JMUkJwU21MdWxkQVZ1aVlVVDZmQXd5TTA5R1BOTXk=

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kapacitor-auth
  namespace: picasa-local
data:
  influxdb-user: YWRtaW4=
  influxdb-password: RE9FdEU5bWdMRFNhVUN3ZWNJYmZZSHNEZ3R0cTV6cnc=

