connector:
  agentId: "agentId test"
  appName: KUBERNETES
  appType: KUBERNETES
  controllerAddr: "0.0.0.0:8099"
  logLevel: 2
  enabled: true
  natsFilestoreDir: natsstore
  natsStoreType: FILE
  batchEvents: 0s
  batchMetrics: 0s
  batchMaxBytes: 10
tcgConnections: 
  - id: 1
    hostName: test
    enabled: true
    isChild: false
    isLocal: true
metricsProfile:
  name: kubernetes-profile-1
  profileType: kubernetes
  id: 3
  connectorId: 4
  metrics:
    - metricType: Gauge
      computeType: Query
      warningThreshold: -1
      criticalThreshold: -1
      name: cpu.allocated
      id: 17
      customName:
      description: Total CPU space allocated
      monitored: true
      graphed: false
      serviceType: Nodes
      sourceType:
      aggregateType: average
      expression:
      format:
      filters: []
      extensions: {}
      metricsProfileId: 3
    - metricType: Gauge
      computeType: Query
      warningThreshold: -1
      criticalThreshold: -1
      name: cpu.cores
      id: 18
      customName:
      description: Number of cores available in the system
      monitored: true
      graphed: false
      serviceType: Nodes
      sourceType:
      aggregateType: average
      expression:
      format:
      filters: []
      extensions: {}
      metricsProfileId: 3
    - metricType: Gauge
      computeType: Query
      warningThreshold: -1
      criticalThreshold: -1
      name: memory.allocated
      id: 19
      customName:
      description: Total memory space allocated
      monitored: true
      graphed: false
      serviceType: Nodes
      sourceType:
      aggregateType: average
      expression:
      format:
      filters: []
      extensions: {}
      metricsProfileId: 3
    - metricType: Gauge
      computeType: Query
      warningThreshold: -1
      criticalThreshold: -1
      name: memory.capacity
      id: 20
      customName:
      description: Memory capacity available in the system
      monitored: true
      graphed: false
      serviceType: Nodes
      sourceType:
      aggregateType: average
      expression:
      format:
      filters: []
      extensions: {}
      metricsProfileId: 3
    - metricType: Gauge
      computeType: Query
      warningThreshold: -1
      criticalThreshold: -1
      name: cpu
      id: 21
      customName:
      description: Total CPU space allocated
      monitored: true
      graphed: false
      serviceType: Pods
      sourceType:
      aggregateType: average
      expression:
      format:
      filters: []
      extensions: {}
      metricsProfileId: 3
    - metricType: Gauge
      computeType: Query
      warningThreshold: -1
      criticalThreshold: -1
      name: memory
      id: 22
      customName:
      description: Total memory space allocated
      monitored: true
      graphed: false
      serviceType: Pods
      sourceType:
      aggregateType: average
      expression:
      format:
      filters: []
      extensions: {}
      metricsProfileId: 3

